apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      protocol: TCP
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: {{ .Values.container.targetPort }}





