version: "2"
# local development
services:
  api_gateway:
    restart: always
    depends_on:
      - redis
    networks:
      - wtcnet
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-microservice
    environment:
      REDIS_PASSWORD: "rediska"
      JWT_SECRET: "secret-ke1"
      REDIS_ADDR: "redis:6379"
      USER_SERVICE_URL: "http://user-microservice:8080/api"
    ports:
      - "80:8080"
  redis:
    image: redis:latest
    networks:
      - wtcnet
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "rediska"

networks:
  wtcnet:
    external: true
