version: "2"

services:
  api_gateway:
    restart: always
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wtc-api_gateway
    ports:
      - "80:8080"
networks:
  backend: