version: "3"
# to be launched with additional arguments like
#AWS_ACCESS_KEY_ID=akeyId AWS_SECRET_ACCESS_KEY=akey AWS_REGION=region
#AWS_BUCKET=bucket docker compose up --build
# or you can configure the .env
services:
  app:
    restart: on-failure
    networks:
      - wtcnet
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-microservice
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
    ports:
      - "8989:8080"

networks:
  wtcnet:
    external: true