version: "3"

services:
  app:
    restart: on-failure
    networks:
      - wtcnet
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-service
    ports:
      - "8080:8080"

networks:
  wtcnet:
    external: true