apiVersion: v1
kind: Service

metadata:
  name: postgres-user-service
  namespace: {{.Values.namespace}}
  labels:
    app: postgres-user-service
spec:
  ports:
  - port: 5433
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres-deploy