apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-storage
  namespace: {{.Values.namespace}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

