apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-storage
  namespace: {{.Values.namespace}}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi