version: "3"

services:
  app:
    restart: on-failure
    depends_on:
      - db
      - flyway-migration
    networks:
      - wtcnet
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-microservice
    environment:
      DB_HOST: db
      DB_PORT: 5445
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_MAX_ATTEMPTS: 5
    ports:
      - "8080:8080"

  flyway-migration:
    image: flyway/flyway
    restart: on-failure
    depends_on:
      - db
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://db:5445/postgres
      - FLYWAY_SCHEMAS=public
    volumes:
      - ./.helm/migration:/flyway/sql
    command:
      - migrate
    networks:
      - wtcnet
  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5445" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - wtcnet
    volumes:
      - .:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp
    command: -p 5445
    ports:
      - "5445:5445"

networks:
  wtcnet:
    external: true