version: "2"

services:
  app:
    restart: always
    networks:
      default:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wtc-user-service
    ports:
      - "4000:8080"
  db:
    image: postgres:latest
    networks:
      default:
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp
    ports:
      - "5432:5432"
networks:
  default:
