image:
  repository: ""
  tag: ""

container:
  port: 10000
  targetPort: 10000
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

redis:
  ns: default
  password: ""