---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.michaeldeveloper.com
      http:
        paths:
          - path: /test
            backend:
              service:
                name: wtc-api-gateway
                port:
                  number: 80
            pathType: Prefix