apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    project: {{ .Release.Name }}-app-deploy
  ports:
    - name: {{ .Release.Name }}-listener
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      protocol: TCP
  type: ClusterIP