apiVersion: v1
kind: Service
metadata:
  name: wtc-user-service
spec:
  selector:
    app: {{ .Release.Name }}-deploy
  ports:
    - name: {{ .Release.Name }}-listener
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      protocol: TCP
  type: ClusterIP