apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetPort }}
      protocol: TCP
  type: LoadBalancer