name: cd

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    uses: ./.github/workflows/build.workflow.yml
    with:
      version: $(git rev-parse --short "$GITHUB_SHA")
  
  deploy-user-service:
    runs-on: ubuntu-latest
    env:
      VERSION: $(git rev-parse --short "$GITHUB_SHA")
    steps: 
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-wtc
      
    - name: Deploy
      # helm install user-service ./user_service/.helm
      run: |
           helm --debug upgrade --install \
           --set image.tag=${{ env.VERSION }} \
           user-service user_service/.helm
