name: ci-cd-pipeline-to-aws
env:
  EB_PACKAGE_S3_BUCKET_NAME : "wtc-api-packages"
  EB_APPLICATION_BEANSTALK  : "Wtc"
  EB_ENVIRONMENT_ENV        : "Wtc-env"
  DEPLOY_PACKAGE_NAME       : "wtc_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
      
    - name: Create zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }} 
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print Happy Message for CI
      run: echo "CI pipeline part finished successfully"
      
