name: ci-cd-pipeline-to-aws
env:
  EB_PACKAGE_S3_BUCKET_NAME : "wtc-api-packages"
  EB_APPLICATION_BEANSTALK  : "Wtc"
  EB_ENVIRONMENT_ENV        : "Wtc-env"
  DEPLOY_PACKAGE_NAME       : "wtc_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
      - master

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
      
    - name: Create zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
